--------------------------------------------------------
--  File created - Sunday-August-23-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TTO_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_ACCOUNT" 
   (	"ACCOUNT_ID" NUMBER(19,0), 
	"IS_DELETE" NUMBER(1,0), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(19,0), 
	"STORE_ID" NUMBER(19,0), 
	"USER_PROFILE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_ADMIN
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_ADMIN" 
   (	"ADMIN_ID" NUMBER(19,0), 
	"LOGIN_NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_COLLECT
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_COLLECT" 
   (	"COLLECT_ID" NUMBER(19,0), 
	"STORE" NUMBER(19,0), 
	"USER_PROFILE" NUMBER(19,0), 
	"USER_PROFILE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_COMMENT
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_COMMENT" 
   (	"COMMENT_ID" NUMBER(19,0), 
	"CONTEXT" VARCHAR2(255 CHAR), 
	"DELIVER_TIME" NUMBER(19,2), 
	"POINT" NUMBER(19,2), 
	"USER_PROFILE" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_CONFIG
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_CONFIG" 
   (	"CONFIG_ID" NUMBER(19,0), 
	"CONFIG_NAME" VARCHAR2(255 CHAR), 
	"CONFIG_VAL" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_LOCATION
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_LOCATION" 
   (	"LOCATION_ID" NUMBER(19,0), 
	"AREA" VARCHAR2(255 CHAR), 
	"CITY" VARCHAR2(255 CHAR), 
	"PLACE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_ORDER
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_ORDER" 
   (	"ORDER_ID" NUMBER(19,0), 
	"CONT_NAME" VARCHAR2(255 CHAR), 
	"CONT_PHONE" VARCHAR2(255 CHAR), 
	"CREATE_TIME" TIMESTAMP (6), 
	"DETAIL_LOC" VARCHAR2(255 CHAR), 
	"END_TIME" TIMESTAMP (6), 
	"IS_DELETE" NUMBER(1,0), 
	"ORDER_NUMBER" VARCHAR2(255 CHAR), 
	"PAY_WAY" VARCHAR2(255 CHAR), 
	"REMAKRS" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(255 CHAR), 
	"STORE_ID" NUMBER(19,0), 
	"VERSION" NUMBER(19,0), 
	"COMMENT_ID" NUMBER(19,0), 
	"USER_PROFILE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_ORDER_ITEM
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_ORDER_ITEM" 
   (	"ORDER_ITEM_ID" NUMBER(19,0), 
	"AMOUNT" NUMBER(19,2), 
	"PRICE" NUMBER(19,2), 
	"PRODUCT" NUMBER(19,0), 
	"ORDER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_PRO
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_PRO" 
   (	"PRO_ID" NUMBER(19,0), 
	"IS_DELETE" NUMBER(1,0), 
	"POINT" NUMBER(19,2), 
	"PRICE" NUMBER(19,2), 
	"PRO_NAME" VARCHAR2(255 CHAR), 
	"PRO_PIC_URL" VARCHAR2(255 CHAR), 
	"PRO_SALES_VOL" NUMBER(19,2), 
	"STORE_ID" NUMBER(19,0), 
	"VERSION" NUMBER(19,0), 
	"PRODUCT_LABEL" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_PRO_LABEL
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_PRO_LABEL" 
   (	"PRO_LABEL_ID" VARCHAR2(255 CHAR), 
	"PRO_LABEL_NAME" VARCHAR2(255 CHAR), 
	"STORE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_STORE
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_STORE" 
   (	"STORE_ID" NUMBER(19,0), 
	"ANNOUNCEMENT" VARCHAR2(255 CHAR), 
	"AVG_DELIVER_TIME" NUMBER(19,2), 
	"AVG_POINT" NUMBER(19,2), 
	"DELIVER_FEE" NUMBER(19,2), 
	"DETAIL_LOC" VARCHAR2(255 CHAR), 
	"IS_DELETE" NUMBER(1,0), 
	"PHONE" VARCHAR2(255 CHAR), 
	"SERVICE_BEGIN_TIME" TIMESTAMP (6), 
	"SERVICE_END_TIME" TIMESTAMP (6), 
	"STARTING_FEE" NUMBER(19,2), 
	"STORE_NAME" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(19,0), 
	"LOCATION" NUMBER(19,0), 
	"STORE_PROFILE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_STORE_PROFILE
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_STORE_PROFILE" 
   (	"STORE_PROFILE_ID" NUMBER(19,0), 
	"ID_CARD_NUMBER" VARCHAR2(255 CHAR), 
	"ID_CARD_PIC_URL" VARCHAR2(255 CHAR), 
	"IS_DELETE" NUMBER(1,0), 
	"LIC_PIC_URL" VARCHAR2(255 CHAR), 
	"REAL_NAME" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Table TTO_USER_PROFILE
--------------------------------------------------------

  CREATE TABLE "WANGCD"."TTO_USER_PROFILE" 
   (	"USER_PROFILE_ID" NUMBER(19,0), 
	"FUND" NUMBER(19,2), 
	"IS_DELETE" NUMBER(1,0), 
	"VERSION" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044714
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044714" ON "WANGCD"."TTO_ACCOUNT" ("ACCOUNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044716
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044716" ON "WANGCD"."TTO_ADMIN" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044718
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044718" ON "WANGCD"."TTO_COLLECT" ("COLLECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044720
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044720" ON "WANGCD"."TTO_COMMENT" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044722
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044722" ON "WANGCD"."TTO_CONFIG" ("CONFIG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044724
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044724" ON "WANGCD"."TTO_LOCATION" ("LOCATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044726
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044726" ON "WANGCD"."TTO_ORDER" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044728
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044728" ON "WANGCD"."TTO_ORDER_ITEM" ("ORDER_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044730
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044730" ON "WANGCD"."TTO_PRO" ("PRO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044732
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044732" ON "WANGCD"."TTO_PRO_LABEL" ("PRO_LABEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044734
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044734" ON "WANGCD"."TTO_STORE" ("STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044736
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044736" ON "WANGCD"."TTO_STORE_PROFILE" ("STORE_PROFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0044738
--------------------------------------------------------

  CREATE UNIQUE INDEX "WANGCD"."SYS_C0044738" ON "WANGCD"."TTO_USER_PROFILE" ("USER_PROFILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE" ;
--------------------------------------------------------
--  Constraints for Table TTO_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_ACCOUNT" ADD PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_ACCOUNT" MODIFY ("ACCOUNT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_ADMIN
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_ADMIN" ADD PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_COLLECT
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_COLLECT" ADD PRIMARY KEY ("COLLECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_COLLECT" MODIFY ("COLLECT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_COMMENT
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_COMMENT" ADD PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_COMMENT" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_CONFIG
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_CONFIG" ADD PRIMARY KEY ("CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_CONFIG" MODIFY ("CONFIG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_LOCATION
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_LOCATION" ADD PRIMARY KEY ("LOCATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_LOCATION" MODIFY ("LOCATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_ORDER
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_ORDER" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_ORDER" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_ORDER_ITEM" ADD PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_ORDER_ITEM" MODIFY ("ORDER_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_PRO
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_PRO" ADD PRIMARY KEY ("PRO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_PRO" MODIFY ("PRO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_PRO_LABEL
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_PRO_LABEL" ADD PRIMARY KEY ("PRO_LABEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_PRO_LABEL" MODIFY ("PRO_LABEL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_STORE
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_STORE" ADD PRIMARY KEY ("STORE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_STORE" MODIFY ("STORE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_STORE_PROFILE
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_STORE_PROFILE" ADD PRIMARY KEY ("STORE_PROFILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_STORE_PROFILE" MODIFY ("STORE_PROFILE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TTO_USER_PROFILE
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_USER_PROFILE" ADD PRIMARY KEY ("USER_PROFILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WMYDX_SPACE"  ENABLE;
  ALTER TABLE "WANGCD"."TTO_USER_PROFILE" MODIFY ("USER_PROFILE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TTO_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_ACCOUNT" ADD CONSTRAINT "FK_2AHJMSUTS2DB684IME5SSX4M8" FOREIGN KEY ("STORE_ID")
	  REFERENCES "WANGCD"."TTO_STORE" ("STORE_ID") ENABLE;
  ALTER TABLE "WANGCD"."TTO_ACCOUNT" ADD CONSTRAINT "FK_P0NMSWKWU1X39SXU6JV56OE58" FOREIGN KEY ("USER_PROFILE_ID")
	  REFERENCES "WANGCD"."TTO_USER_PROFILE" ("USER_PROFILE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TTO_COLLECT
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_COLLECT" ADD CONSTRAINT "FK_7K8X48D5L0P8BB1D1A7RH1VL5" FOREIGN KEY ("USER_PROFILE")
	  REFERENCES "WANGCD"."TTO_USER_PROFILE" ("USER_PROFILE_ID") ENABLE;
  ALTER TABLE "WANGCD"."TTO_COLLECT" ADD CONSTRAINT "FK_8U1XI5OPUCGLGPO361DY3EYA9" FOREIGN KEY ("USER_PROFILE_ID")
	  REFERENCES "WANGCD"."TTO_USER_PROFILE" ("USER_PROFILE_ID") ENABLE;
  ALTER TABLE "WANGCD"."TTO_COLLECT" ADD CONSTRAINT "FK_F0YDE78WFODKLL5YOHY5AOXEQ" FOREIGN KEY ("STORE")
	  REFERENCES "WANGCD"."TTO_STORE" ("STORE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TTO_COMMENT
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_COMMENT" ADD CONSTRAINT "FK_L8WAES2VAG1F5R2DS9X8OIJTI" FOREIGN KEY ("USER_PROFILE")
	  REFERENCES "WANGCD"."TTO_USER_PROFILE" ("USER_PROFILE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TTO_ORDER
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_ORDER" ADD CONSTRAINT "FK_33N433VYQNTE6KAGQEABCFQ05" FOREIGN KEY ("STORE_ID")
	  REFERENCES "WANGCD"."TTO_STORE" ("STORE_ID") ENABLE;
  ALTER TABLE "WANGCD"."TTO_ORDER" ADD CONSTRAINT "FK_5GRC5QT1CI5RGWTE6XSK392A5" FOREIGN KEY ("COMMENT_ID")
	  REFERENCES "WANGCD"."TTO_COMMENT" ("COMMENT_ID") ENABLE;
  ALTER TABLE "WANGCD"."TTO_ORDER" ADD CONSTRAINT "FK_JVBFKA7BWVPGE46YOLIE3G9OV" FOREIGN KEY ("USER_PROFILE_ID")
	  REFERENCES "WANGCD"."TTO_USER_PROFILE" ("USER_PROFILE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TTO_ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_ORDER_ITEM" ADD CONSTRAINT "FK_146Y7KE7KFAV9W84AVPN3UKCX" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "WANGCD"."TTO_ORDER" ("ORDER_ID") ENABLE;
  ALTER TABLE "WANGCD"."TTO_ORDER_ITEM" ADD CONSTRAINT "FK_QK5AOBVLNKPNENQYY0V0PQUVO" FOREIGN KEY ("PRODUCT")
	  REFERENCES "WANGCD"."TTO_PRO" ("PRO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TTO_PRO
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_PRO" ADD CONSTRAINT "FK_7JIS03SP0KF8R36Y1WUN4H3L0" FOREIGN KEY ("PRODUCT_LABEL")
	  REFERENCES "WANGCD"."TTO_PRO_LABEL" ("PRO_LABEL_ID") ENABLE;
  ALTER TABLE "WANGCD"."TTO_PRO" ADD CONSTRAINT "FK_Q8DG1XSCEYUBPCXNH4P3PPXTE" FOREIGN KEY ("STORE_ID")
	  REFERENCES "WANGCD"."TTO_STORE" ("STORE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TTO_PRO_LABEL
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_PRO_LABEL" ADD CONSTRAINT "FK_P4DJ903S8Y56G14QN9KFBGEPR" FOREIGN KEY ("STORE_ID")
	  REFERENCES "WANGCD"."TTO_STORE" ("STORE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TTO_STORE
--------------------------------------------------------

  ALTER TABLE "WANGCD"."TTO_STORE" ADD CONSTRAINT "FK_65GQ0SW34VCOB32D91WXLEOSG" FOREIGN KEY ("LOCATION")
	  REFERENCES "WANGCD"."TTO_LOCATION" ("LOCATION_ID") ENABLE;
  ALTER TABLE "WANGCD"."TTO_STORE" ADD CONSTRAINT "FK_ASRLW186XOQOPY2GAIM5C424Y" FOREIGN KEY ("STORE_PROFILE_ID")
	  REFERENCES "WANGCD"."TTO_STORE_PROFILE" ("STORE_PROFILE_ID") ENABLE;

--------------------------------------------------------
--  File created - Sunday-August-23-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_ACCOUNT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_ACCOUNT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_ADMIN_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_ADMIN_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_COLLECT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_COLLECT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_COMMENT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_COMMENT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_CONFIG_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_CONFIG_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_LOCA_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_LOCA_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_ORDER_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_ORDER_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_ORDER_ITEM_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_ORDER_ITEM_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_PRO_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_PRO_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_PRO_LABEL_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_PRO_LABEL_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_STORE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_STORE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TTO_STORE_PRO_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WANGCD"."SEQ_TTO_STORE_PRO_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
